#!/bin/bash

CLIENT_ID=eb03e678-1326-43af-af68-94fc1bfe0bfa
CLIENT_SECRET="ta-secret.yO@bwWV%pmJUrh&h"
AUDIENCE=https://fleet-api.prd.na.vn.cloud.tesla.com

curl --request POST \
--header 'CONTENT-TYPE: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode "client_id=$CLIENT_ID" \
--data-urlencode "client_secret=$CLIENT_SECRET" \
--data-urlencode 'scope=openid vehicle_device_data vehicle_cmds vehicle_charging_cmds' \
--data-urlencode "audience=$AUDIENCE" \
'https://auth.tesla.com/oauth2/v3/token'